SELECT
        B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, 
        SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM
        BOOK B, AUTHOR A,
        (SELECT BOOK_ID, SALES_DATE, SUM(SALES) AS SALES
        FROM    BOOK_SALES 
        WHERE   SALES_DATE LIKE '2022-01-%'
        GROUP BY
                BOOK_ID, SALES_DATE) S
WHERE
        B.BOOK_ID = S.BOOK_ID and B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY
        B.AUTHOR_ID, B.CATEGORY
ORDER BY
        B.AUTHOR_ID, B.CATEGORY DESC
        