SELECT
        ITEM_ID, ITEM_NAME, RARITY
FROM
        ITEM_INFO
WHERE
        ITEM_ID NOT IN (SELECT  I1.ITEM_ID
        FROM     ITEM_INFO I1, ITEM_TREE I2
        WHERE    I1.ITEM_ID = I2.PARENT_ITEM_ID)
ORDER BY
        ITEM_ID DESC