SELECT
        C1.CAR_ID, C1.CAR_TYPE,
        DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100 AS FEE
FROM
        CAR_RENTAL_COMPANY_CAR C1
JOIN
        CAR_RENTAL_COMPANY_DISCOUNT_PLAN C3
ON
        C1.CAR_TYPE = C3.CAR_TYPE
WHERE
        C1.CAR_TYPE IN ('세단','SUV') and
        DURATION_TYPE = '30일 이상' and
        C1.CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE <= '2022-11-30'
              AND END_DATE >= '2022-11-01'
        ) and
        DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100 >= 500000 and
        DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100 < 2000000
ORDER BY
        FEE DESC, C1.CAR_TYPE, C1.CAR_ID DESC