SELECT
        T1.ITEM_ID, T2.ITEM_NAME, T2.RARITY
FROM
        (SELECT ITEM_TREE.ITEM_ID
        FROM ITEM_INFO, ITEM_TREE
        WHERE RARITY = "RARE" AND ITEM_INFO.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID) T1
JOIN
        ITEM_INFO T2
ON      
        T1.ITEM_ID = T2.ITEM_ID
ORDER BY
        T2.ITEM_ID DESC