SELECT
        E.ID, E.GENOTYPE, C.GENOTYPE AS PARENT_GENOTYPE
FROM
        ECOLI_DATA E
  JOIN
        ECOLI_DATA C
  ON   
        E.PARENT_ID = C.ID
WHERE
        E.PARENT_ID is NOT NULL
        AND (E.GENOTYPE & C.GENOTYPE) = C.GENOTYPE
ORDER BY
        ID