SELECT
        DISTINCT C1.CAR_ID
FROM
        CAR_RENTAL_COMPANY_CAR C1
JOIN
        CAR_RENTAL_COMPANY_RENTAL_HISTORY C2
ON
        C1.CAR_ID = C2.CAR_ID
WHERE
        CAR_TYPE = '세단' AND MONTH(START_DATE) = 10
ORDER BY
        C1.CAR_ID DESC