-- 코드를 입력하세요
SELECT TITLE, BOARD_ID, REPLY_ID, T2.WRITER_ID, T2.CONTENTS, DATE_FORMAT(T2.CREATED_DATE, '%Y-%m-%d') 
FROM USED_GOODS_BOARD T1 
JOIN USED_GOODS_REPLY T2 USING (BOARD_ID) 
WHERE T1.CREATED_DATE LIKE '2022-10-%' ORDER BY T2.CREATED_DATE, TITLE